/*
 * WINGS Operating System
 * Copyright (C) 2016 Alyssa Rosenzweig
 * 
 * This file is part of WINGS.
 * 
 * WINGS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * WINGS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with WINGS.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * test program for working with streams
 * for clarification, this is meant to run under GNU/Linux, not WINGS
 * In practice, this will be generated by the WINGS compiler from a Lisp program
 * 
 * screenOut <- keyboardInput.map(x => (x.charToInt + 1).intToChar)
 */

#include <stdio.h>
#include "libstream.h"

ReactiveStream in, out;

void screenOut(void* node) {
    putchar( (char) node);
}

void lambda0(void* node) {
    pushStream(&out, (void*) (char) node + 1);
}

int main(int argc, char** argv) {
    // establish stdin
    out = makeStream();
    registerStream(&out, screenOut);
    in = makeStream();

    // some logic
    registerStream(&in, lambda0);

    // main loop
    char c;
    while(c = getchar()) {
        pushStream(&in, (void*) c);
    }
}
